[project]
name = "duckconvert"
version = "0.1.0"
description = "A file conversion tool using DuckDB via it's Python API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.0",
]

[tool.hatch]
option = "..."
table1.option = "..."
table2.option = "..."
